### ISSUE TITLE
Project promotes racist, androcentrist material

### ISSUE THREAD

**Issue by colepeters** [edankwan/penis.js#7]
@edankwan, I don’t know what your intentions were in creating this project, but personally I find it incredibly offensive on a number of levels:

- the entire project is androcentrist — that is, creating and influencing a male-centric environment; there is enough of this in technology already without adding to it
- the documentation provided is highly racist (using code to make jokes about genitalia in African men as compared to Asian men)
- the document is highly crass and contributes to an environment in which anatomy is used as a basis for offensive humour

You may feel that if someone finds this project offensive they should simply look away and not pay any attention; however, know that projects like this are instrumental in alienating women, the non-cis-gendered, or indeed anyone who finds the topic of male genitalia or racism discomforting at best (also consider that children are learning to code and they don’t need to be exposed to this sort of material, either).

I hope that you consider this issue within the framework of an industry that is already androcentric, heteronormative and dominated by white supremacy enough as it is. Please don’t contribute to furthering these stereotypes and hugely offensive attitudes.

**Comment by edankwan** [comment]
The entire project is simply a joke. Yes, I use those stereotypes in the readme.md and it was part of my joke.

For the 1st argument, I didn't imply anything like that anywhere in my project. If I did, please point it out. As you might not notice, I also have a [vagina.js](https://github.com/edankwan/vagina.js).

For the 2rd argument - Being racist? Hey, I myself am Chinese, the one stereotypically with small dick but I seriously don't find this project **racist** in a hateful way. Of coz I experienced the racist situation as an Asian living in the western country. But I can tell you, this is not racist at least it is no-harm-done racist. I guess it is probably part of your **white guilt** encourage you to link it to racism.

However, there is one good point you mentioned I think it is totally right and that's why I labeled this issue as an **enhancement**. Yes, I am gonna add a **PG** sign at to top of the readme document in case of children stumble into this project.

Thank you for your contribution.

**Comment by colepeters** [comment]
Just because you yourself don’t find something offensive does not mean that it is, therefore, not offensive at all. I think this is important to remember.

Regarding your statement that “this is not racist” — racism is defined as:
> the belief that all members of each race possess characteristics, abilities, or qualities specific to that race, especially so as to distinguish it as inferior or superior to another race or races

Who are you to judge whether any harm has been done, based only on your opinion of the material?

This has nothing to do with my so-called “white guilt”, but rather a widely-held belief that there is enough  racism in the technology industry as it is, without adding more on top of it.

As for the androcentrism — the fact that you have a vagina.js project doesn’t imply that you are impartial to sex, but instead that you’ve demonstrated distasteful treatment of both.

**Comment by colepeters** [comment]
You might also want to read this article on the topic of sexist humour: http://geekfeminism.wikia.com/wiki/Sexist_humor

**Comment by edankwan** [comment]
Sorry man, I really don't see where did I imply any sexist or racist content in my work. But you assume that I am and put some links and quote to imply that I am.

I guess at this point for me to win this conversation is to quote the bible:

>Know therefore that the Lord your God is God; he is the faithful God, keeping his covenant of love to a thousand generations of those who love him and keep his commandments.
**Deuteronomy 7:9 NIV**

Just a random quote, totally irrelevant like what you did. I hope with God among us, this issue can be resolved.

If you think that the PG sign is not enough. I am open for suggestion like to use **18 or above** if you think it is more appropriate. I would love to put your name under the PG sign if you don't mind because your suggestion was really helpful.

**Comment by colepeters** [comment]
Thanks @edankwan, but I’d rather not have my name anywhere on this project.

**Comment by edankwan** [comment]
I jsut realized that you are a designer, I probably need some input of design from you if you don't mind. I did a quick design who is what I am using currently:

![pg](https://cloud.githubusercontent.com/assets/989103/6599603/b65b4c00-c802-11e4-8e38-4311f83d5b06.jpg)

But then I designed another which looks more pop and children can spot it immediately when they land on the page:
![yellow](https://cloud.githubusercontent.com/assets/989103/6599604/b65c7ad0-c802-11e4-94b4-2d73acca9453.jpg)

This last one I used a triangle background as I know that low poly design is a cool trend in lately:
![triangle](https://cloud.githubusercontent.com/assets/989103/6599602/b659abac-c802-11e4-8b38-a7db958cbeb6.jpg)

So, what do you think?

**Comment by edankwan** [comment]
Also, this one I used crosses to symbolize Jesus. I guess it helps the who parental guidance thing. And I skewed the text for a little bit to enhance the perspective as well. Is it better?

![crosses](https://cloud.githubusercontent.com/assets/989103/6600009/d583b692-c804-11e4-9347-d600ed90d4af.jpg)

**Comment by edankwan** [comment]
I just figured something better. What do you think? I used some movie poster as reference. Looks 10 times cleaner:

![poster](https://cloud.githubusercontent.com/assets/989103/6600266/872af7f6-c806-11e4-8193-9d15320b057d.jpg)

**Comment by Kyokou** [comment]
>Just because you yourself don’t find something offensive does not mean that it is, therefore, not offensive at all.

This offends me. Educate yourself.
https://www.youtube.com/watch?v=ceS_jkKjIgo

**Comment by edankwan** [comment]
@Kyokou thank you for sharing :D

**Comment by frankypoo** [comment]
@edankwan as a polygender attribution-kin, I find it highly offensive you didn't put @colepeters' name on the PG image. Please check your attribution privilege and give him due credit in the repo.

**Comment by edankwan** [comment]
@frankypoo apparently @colepeters doesn't want his name on anywhere on this project https://github.com/edankwan/penis.js/issues/7#issuecomment-78282214

**Comment by Kyokou** [comment]
@edankwan 
As a self-identifying name-kin. Cole's name is Cole. His GitHub handle is @colepeters. It's disrespectful to compound the two and treat them as the same thing. His name is his name and his handle is his handle. 

Attributing his handle will solve @frankpoo 's problem while conforming with @colepeters 's wish of not having his name anywhere on the project.

**Comment by snail23** [comment]
```
var vagina = ({});
vagina.fill = penis.head
```

I find this project hilarious.

**Comment by jkoudys** [comment]
Won't somebody _please_ think of the _children_!!

**Comment by ertdfgcb** [comment]
> Just because you yourself don’t find something offensive does not mean that it is, therefore, not offensive at all.
You might find it offensive and take bad feelings from it, but plenty of people find it funny and take equally good feelings from it. Who are you to say your feelings are more important?

**Comment by derek-adair** [comment]
This fucking thread... ROLFOLOLOLOL

**Comment by piedoom** [comment]
this is glorious.

**Comment by robbyoconnor** [comment]
ayy lmao

**Comment by louiz** [comment]
@derek-adair @piedoom @robbyoconnor 
I agree that @colepeters' posts are pretty ridiculous (and sexist), but you should probably leave that issue as it is, instead of changing it into an other endless suite of animated gifs or “lol this thread lmao” like we often see on github when an issue gets publicity from reddit or some other site.

**Comment by robbyoconnor** [comment]
My response is still the same 

![](https://cloud.githubusercontent.com/assets/23088/6890102/2824805e-d672-11e4-986f-dff3ef283f05.jpg)

**Comment by robbyoconnor** [comment]
@colepeters Stop being so tightly wound -- and just appreciate this project for its comical purpose. How the hell you constructed your argument is beyond me. It saddens me how people seem to find offense in the dumbest of things. I'm gonna guess you're also the type that gets offended by [Cards Against Humanity](https://cardsagainsthumanity.com/)...lighten the fuck up. Though you have contributed to this project by creating this issue...thank you.

**Comment by derek-adair** [comment]
@louiz  that offends me.

Really though, I agree with @colepeters message.  But this is NOT the appropriate forum to end the patriarchy, and definitely **not** the right thing to divert any energy to, lest you be trolled.  Really, anything other than making an issue in a gag repo would have done.  A blog post, shit even a website cataloging things that offend you if you want.

Im afraid this is nothing more than a joke, and your time would be much better spent elsewhere.

**Comment by robbyoconnor** [comment]
@derek-adair is right -- the only thing @colepeters  did is provide us trolls some ammo to troll the shit out of him. This is hilarious. For reference [http://github.com/edankwan/vagina.js](vagina.js) exists...so @colepeters  -- just close this issue and move on....you won't have the last word here.

**Comment by louiz** [comment]
> so @colepeters -- just close this issue and move on....

Do you realize that he hasn’t said anything for 22 days? He has probably already moved on, unlike you.
